
  create table "public"."features_client" (
    "id" bigint generated by default as identity not null,
    "dump_id" bigint,
    "start_time" timestamp with time zone,
    "duration" integer,
    "user_agent_data" jsonb,
    "hardware_concurrency" smallint,
    "device_memory" smallint,
    "screen" jsonb,
    "window" jsonb
      );


alter table "public"."features_client" enable row level security;


  create table "public"."features_connection" (
    "id" bigint generated by default as identity not null,
    "dump_id" bigint,
    "start_time" timestamp with time zone,
    "duration" integer,
    "connection_identifier" text,
    "number_of_events" integer,
    "number_of_events_not_getstats" integer,
    "closed" boolean
      );


alter table "public"."features_connection" enable row level security;


  create table "public"."features_metadata" (
    "id" bigint generated by default as identity not null,
    "dump_id" bigint,
    "created_at" timestamp with time zone not null default now(),
    "start_time" timestamp with time zone,
    "url" text,
    "origin" text,
    "useragent" text,
    "client_protocol" text,
    "file_format" smallint,
    "number_peerconnections" smallint
      );


alter table "public"."features_metadata" enable row level security;


  create table "public"."features_track" (
    "id" bigint generated by default as identity not null,
    "connection_id" bigint,
    "start_time" timestamp with time zone,
    "duration" integer,
    "track_identifier" text,
    "kind" text,
    "direction" text
      );


alter table "public"."features_track" enable row level security;

alter table "public"."rtcstats-server" add column "features_processing_start" timestamp with time zone;

alter table "public"."rtcstats-server" add column "features_processing_stop" timestamp with time zone;

alter table "public"."rtcstats-server" drop column "features_url";

alter table "public"."rtcstats-server" drop column "metadata";

CREATE UNIQUE INDEX features_client_pkey ON public.features_client USING btree (id);

CREATE UNIQUE INDEX features_connection_pkey ON public.features_connection USING btree (id);

CREATE UNIQUE INDEX features_metadata_pkey ON public.features_metadata USING btree (id);

CREATE UNIQUE INDEX features_track_pkey ON public.features_track USING btree (id);

alter table "public"."features_client" add constraint "features_client_pkey" PRIMARY KEY using index "features_client_pkey";

alter table "public"."features_connection" add constraint "features_connection_pkey" PRIMARY KEY using index "features_connection_pkey";

alter table "public"."features_metadata" add constraint "features_metadata_pkey" PRIMARY KEY using index "features_metadata_pkey";

alter table "public"."features_metadata" add constraint "features_metadata_dump_id_fkey" FOREIGN KEY (dump_id) REFERENCES public."rtcstats-server"(id) ON UPDATE CASCADE not valid;

alter table "public"."features_metadata" validate constraint "features_metadata_dump_id_fkey";

alter table "public"."features_track" add constraint "features_track_pkey" PRIMARY KEY using index "features_track_pkey";

alter table "public"."features_client" add constraint "features_client_dump_id_fkey" FOREIGN KEY (dump_id) REFERENCES public.features_metadata(id) ON DELETE CASCADE not valid;

alter table "public"."features_client" validate constraint "features_client_dump_id_fkey";

alter table "public"."features_connection" add constraint "features_connection_dump_id_fkey" FOREIGN KEY (dump_id) REFERENCES public.features_metadata(id) ON DELETE CASCADE not valid;

alter table "public"."features_connection" validate constraint "features_connection_dump_id_fkey";

alter table "public"."features_track" add constraint "features_track_connection_id_fkey" FOREIGN KEY (connection_id) REFERENCES public.features_connection(id) ON DELETE CASCADE not valid;

alter table "public"."features_track" validate constraint "features_track_connection_id_fkey";

grant delete on table "public"."features_client" to "anon";

grant insert on table "public"."features_client" to "anon";

grant references on table "public"."features_client" to "anon";

grant select on table "public"."features_client" to "anon";

grant trigger on table "public"."features_client" to "anon";

grant truncate on table "public"."features_client" to "anon";

grant update on table "public"."features_client" to "anon";

grant delete on table "public"."features_client" to "authenticated";

grant insert on table "public"."features_client" to "authenticated";

grant references on table "public"."features_client" to "authenticated";

grant select on table "public"."features_client" to "authenticated";

grant trigger on table "public"."features_client" to "authenticated";

grant truncate on table "public"."features_client" to "authenticated";

grant update on table "public"."features_client" to "authenticated";

grant delete on table "public"."features_client" to "service_role";

grant insert on table "public"."features_client" to "service_role";

grant references on table "public"."features_client" to "service_role";

grant select on table "public"."features_client" to "service_role";

grant trigger on table "public"."features_client" to "service_role";

grant truncate on table "public"."features_client" to "service_role";

grant update on table "public"."features_client" to "service_role";

grant delete on table "public"."features_connection" to "anon";

grant insert on table "public"."features_connection" to "anon";

grant references on table "public"."features_connection" to "anon";

grant select on table "public"."features_connection" to "anon";

grant trigger on table "public"."features_connection" to "anon";

grant truncate on table "public"."features_connection" to "anon";

grant update on table "public"."features_connection" to "anon";

grant delete on table "public"."features_connection" to "authenticated";

grant insert on table "public"."features_connection" to "authenticated";

grant references on table "public"."features_connection" to "authenticated";

grant select on table "public"."features_connection" to "authenticated";

grant trigger on table "public"."features_connection" to "authenticated";

grant truncate on table "public"."features_connection" to "authenticated";

grant update on table "public"."features_connection" to "authenticated";

grant delete on table "public"."features_connection" to "service_role";

grant insert on table "public"."features_connection" to "service_role";

grant references on table "public"."features_connection" to "service_role";

grant select on table "public"."features_connection" to "service_role";

grant trigger on table "public"."features_connection" to "service_role";

grant truncate on table "public"."features_connection" to "service_role";

grant update on table "public"."features_connection" to "service_role";

grant delete on table "public"."features_metadata" to "anon";

grant insert on table "public"."features_metadata" to "anon";

grant references on table "public"."features_metadata" to "anon";

grant select on table "public"."features_metadata" to "anon";

grant trigger on table "public"."features_metadata" to "anon";

grant truncate on table "public"."features_metadata" to "anon";

grant update on table "public"."features_metadata" to "anon";

grant delete on table "public"."features_metadata" to "authenticated";

grant insert on table "public"."features_metadata" to "authenticated";

grant references on table "public"."features_metadata" to "authenticated";

grant select on table "public"."features_metadata" to "authenticated";

grant trigger on table "public"."features_metadata" to "authenticated";

grant truncate on table "public"."features_metadata" to "authenticated";

grant update on table "public"."features_metadata" to "authenticated";

grant delete on table "public"."features_metadata" to "service_role";

grant insert on table "public"."features_metadata" to "service_role";

grant references on table "public"."features_metadata" to "service_role";

grant select on table "public"."features_metadata" to "service_role";

grant trigger on table "public"."features_metadata" to "service_role";

grant truncate on table "public"."features_metadata" to "service_role";

grant update on table "public"."features_metadata" to "service_role";

grant delete on table "public"."features_track" to "anon";

grant insert on table "public"."features_track" to "anon";

grant references on table "public"."features_track" to "anon";

grant select on table "public"."features_track" to "anon";

grant trigger on table "public"."features_track" to "anon";

grant truncate on table "public"."features_track" to "anon";

grant update on table "public"."features_track" to "anon";

grant delete on table "public"."features_track" to "authenticated";

grant insert on table "public"."features_track" to "authenticated";

grant references on table "public"."features_track" to "authenticated";

grant select on table "public"."features_track" to "authenticated";

grant trigger on table "public"."features_track" to "authenticated";

grant truncate on table "public"."features_track" to "authenticated";

grant update on table "public"."features_track" to "authenticated";

grant delete on table "public"."features_track" to "service_role";

grant insert on table "public"."features_track" to "service_role";

grant references on table "public"."features_track" to "service_role";

grant select on table "public"."features_track" to "service_role";

grant trigger on table "public"."features_track" to "service_role";

grant truncate on table "public"."features_track" to "service_role";

grant update on table "public"."features_track" to "service_role";


