
  create table "public"."rtcstats_analysis" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "dump_id" bigint,
    "rtcstats_id" text,
    "schema_version" text,
    "analysis_version" text,
    "observations_version" text,
    "upload_timestamp" timestamp with time zone,
    "experience_score" real,
    "audio_score" real,
    "video_score" real,
    "connectivity_score" real,
    "observations_score" real,
    "observations_count" jsonb,
    "ai_summary" jsonb,
    "user_agent_data" jsonb
      );


  create table "public"."rtcstats_observations" (
    "id" bigint generated by default as identity not null,
    "analysis_id" bigint,
    "pid" text,
    "type" text,
    "severity" text,
    "category" text,
    "first_seen_at" double precision,
    "observation" jsonb
      );


alter table "public"."rtcstats_analysis" enable row level security;

alter table "public"."rtcstats_observations" enable row level security;

create index "rtcstats_analysis_dump_id_idx" on "public"."rtcstats_analysis" ("dump_id");

create index "rtcstats_observations_analysis_id_idx" on "public"."rtcstats_observations" ("analysis_id");

create index "rtcstats_observations_pid_idx" on "public"."rtcstats_observations" ("pid");

CREATE UNIQUE INDEX rtcstats_analysis_pkey ON public.rtcstats_analysis USING btree (id);

CREATE UNIQUE INDEX rtcstats_observations_pkey ON public.rtcstats_observations USING btree (id);

alter table "public"."rtcstats_analysis" add constraint "rtcstats_analysis_pkey" PRIMARY KEY using index "rtcstats_analysis_pkey";

alter table "public"."rtcstats_observations" add constraint "rtcstats_observations_pkey" PRIMARY KEY using index "rtcstats_observations_pkey";

alter table "public"."rtcstats_analysis" add constraint "rtcstats_analysis_dump_id_fkey" FOREIGN KEY (dump_id) REFERENCES public."rtcstats-server"(id) ON UPDATE CASCADE not valid;

alter table "public"."rtcstats_analysis" validate constraint "rtcstats_analysis_dump_id_fkey";

alter table "public"."rtcstats_observations" add constraint "rtcstats_observations_analysis_id_fkey" FOREIGN KEY (analysis_id) REFERENCES public.rtcstats_analysis(id) ON DELETE CASCADE not valid;

alter table "public"."rtcstats_observations" validate constraint "rtcstats_observations_analysis_id_fkey";

grant delete on table "public"."rtcstats_analysis" to "anon";

grant insert on table "public"."rtcstats_analysis" to "anon";

grant references on table "public"."rtcstats_analysis" to "anon";

grant select on table "public"."rtcstats_analysis" to "anon";

grant trigger on table "public"."rtcstats_analysis" to "anon";

grant truncate on table "public"."rtcstats_analysis" to "anon";

grant update on table "public"."rtcstats_analysis" to "anon";

grant delete on table "public"."rtcstats_analysis" to "authenticated";

grant insert on table "public"."rtcstats_analysis" to "authenticated";

grant references on table "public"."rtcstats_analysis" to "authenticated";

grant select on table "public"."rtcstats_analysis" to "authenticated";

grant trigger on table "public"."rtcstats_analysis" to "authenticated";

grant truncate on table "public"."rtcstats_analysis" to "authenticated";

grant update on table "public"."rtcstats_analysis" to "authenticated";

grant delete on table "public"."rtcstats_analysis" to "service_role";

grant insert on table "public"."rtcstats_analysis" to "service_role";

grant references on table "public"."rtcstats_analysis" to "service_role";

grant select on table "public"."rtcstats_analysis" to "service_role";

grant trigger on table "public"."rtcstats_analysis" to "service_role";

grant truncate on table "public"."rtcstats_analysis" to "service_role";

grant update on table "public"."rtcstats_analysis" to "service_role";

grant delete on table "public"."rtcstats_observations" to "anon";

grant insert on table "public"."rtcstats_observations" to "anon";

grant references on table "public"."rtcstats_observations" to "anon";

grant select on table "public"."rtcstats_observations" to "anon";

grant trigger on table "public"."rtcstats_observations" to "anon";

grant truncate on table "public"."rtcstats_observations" to "anon";

grant update on table "public"."rtcstats_observations" to "anon";

grant delete on table "public"."rtcstats_observations" to "authenticated";

grant insert on table "public"."rtcstats_observations" to "authenticated";

grant references on table "public"."rtcstats_observations" to "authenticated";

grant select on table "public"."rtcstats_observations" to "authenticated";

grant trigger on table "public"."rtcstats_observations" to "authenticated";

grant truncate on table "public"."rtcstats_observations" to "authenticated";

grant update on table "public"."rtcstats_observations" to "authenticated";

grant delete on table "public"."rtcstats_observations" to "service_role";

grant insert on table "public"."rtcstats_observations" to "service_role";

grant references on table "public"."rtcstats_observations" to "service_role";

grant select on table "public"."rtcstats_observations" to "service_role";

grant trigger on table "public"."rtcstats_observations" to "service_role";

grant truncate on table "public"."rtcstats_observations" to "service_role";

grant update on table "public"."rtcstats_observations" to "service_role";
