alter table "public"."rtcstats-server" add column "new_id" bigint generated by default as identity not null;

alter table "public"."rtcstats-server" drop column id;

alter table "public"."rtcstats-server" rename column new_id to id;

create unique index "rtcstats-server_pkey" on public."rtcstats-server" using btree (id);

alter table "public"."rtcstats-server" add constraint "rtcstats-server_pkey" primary key using index "rtcstats-server_pkey";
